### ISSUE TITLE
VS 2017 build fails in system_allocator.cc

### ISSUE THREAD

**Issue by drlight-code** [Philip-Trettner/clean-core#176]
Build log is attached, the missing symbols look like a missing <malloc.h> include which should however be included for `CC_OS_WINDOWS`
[build_log_clean_core_vs2017.txt](https://github.com/project-arcana/clean-core/files/14404003/build_log_clean_core_vs2017.txt)

```c++
#if defined(CC_OS_WINDOWS)
#define CC_USE_ALIGNED_MALLOC 1
#else
#define CC_USE_ALIGNED_MALLOC 0
#endif

#if defined(CC_OS_LINUX)
#define CC_USE_ALIGNED_ALLOC 1
#else
#define CC_USE_ALIGNED_ALLOC 0
#endif

#if CC_USE_ALIGNED_ALLOC
#include <cstdlib>
#include <malloc.h>
#endif
```

**Comment by Philip-Trettner** [comment]
Should be fixed
