### ISSUE TITLE
__builtin_trap() from CC_ASSERT trashes stack on Linux/gcc

### ISSUE THREAD

**Issue by drlight-code** [Philip-Trettner/clean-core#180]
The `__builtin_trap` implementation of GCC causes an illegal instruction to be executed. This raises a SIGILL, however the stack is already corrupted when GDB breaks, which is quite inconvenient. Reading up on this, simply issuing a SIGTRAP seems to be regarded a fairly portable method on POSIX systems. On my system (GCC 14.2.1, GDB 15.2) this gives a proper debug trace on assert. Are there any reasons why we have to rely on `__builtin_trap`?

**Comment by Philip-Trettner** [comment]
I always got clean stack traces so it was never an issue.

Still, a breakpoint should be recoverable, which builtin_trap is not.

I switched it to SIGTRAP in commit 770f040504b6cb932ac03d32342504cf18070c04

Let me know if this works for you

**Comment by drlight-code** [comment]
Works just fine here! Thank you, closing :+1:
